# Generated by Django 5.2 on 2025-04-10 14:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_waterintake_glasses_waterintake_amount_taken_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='activity',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='date',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='user',
        ),
        migrations.AddField(
            model_name='workout',
            name='calories_burned_per_min',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='description',
            field=models.TextField(default='General Workout'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='watergoal',
            name='daily_goal',
            field=models.PositiveIntegerField(help_text='Enter daily water intake goal in ml'),
        ),
        migrations.AlterField(
            model_name='waterintake',
            name='amount_taken',
            field=models.PositiveIntegerField(help_text='Amount taken today in ml'),
        ),
        migrations.AlterField(
            model_name='waterintake',
            name='date',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='WorkoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_minutes', models.PositiveIntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.workout')),
            ],
        ),
    ]
