# Generated by Django 5.2 on 2025-04-10 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_activity_workout_name_remove_workout_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='calories_burned_per_min',
        ),
    ]
