# Generated by Django 5.2 on 2025-04-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_workout_calories_burned_per_min'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutlog',
            name='duration_minutes',
        ),
        migrations.AddField(
            model_name='workoutlog',
            name='progress',
            field=models.TextField(default='No Progress'),
            preserve_default=False,
        ),
    ]
