# Generated by Django 5.2 on 2025-04-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_meal_name_alter_meal_date_alter_meal_meal_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='waterintake',
            name='amount_taken',
        ),
        migrations.AddField(
            model_name='waterintake',
            name='amount',
            field=models.PositiveIntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='watergoal',
            name='daily_goal',
            field=models.PositiveIntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='waterintake',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
