# Generated by Django 5.2 on 2025-04-11 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_waterintake_amount_taken_waterintake_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='description',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='meal_type',
        ),
        migrations.AddField(
            model_name='meal',
            name='calories',
            field=models.PositiveIntegerField(default=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meal',
            name='carbs',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='meal',
            name='category',
            field=models.CharField(choices=[('Fruits', 'Fruits'), ('Grains', 'Grains'), ('Protein', 'Protein'), ('Vegetables', 'Vegetables'), ('Dairy', 'Dairy'), ('Snack', 'Snack'), ('Beverage', 'Beverage'), ('Other', 'Other')], default='Other', max_length=20),
        ),
        migrations.AddField(
            model_name='meal',
            name='fats',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='meal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='meal_images/'),
        ),
        migrations.AddField(
            model_name='meal',
            name='protein',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='meal',
            name='date',
            field=models.DateField(),
        ),
    ]
