# Generated by Django 5.2 on 2025-04-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_meal_description_remove_meal_meal_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='calories',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='meal',
            name='carbs',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='meal',
            name='category',
            field=models.CharField(choices=[('Fruits', 'Fruits'), ('Grains', 'Grains'), ('Protein', 'Protein'), ('Vegetables', 'Vegetables'), ('Dairy', 'Dairy')], max_length=20),
        ),
        migrations.AlterField(
            model_name='meal',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='fats',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='meal',
            name='protein',
            field=models.FloatField(),
        ),
    ]
